# Generated by Django 3.2.6 on 2021-08-07 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('product_tag', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image_url', models.URLField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='FashionApp.category')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
