# Generated by Django 3.2.6 on 2021-08-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default='Black', max_length=20),
        ),
    ]
